# -*- coding: utf-8 -*-
"""WakkaInternshipTask4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ui4bLS03vVjf3gmZHYX_Y4br2L54ktn4
"""

import pandas as pd

#Now we create a function that prepare the data for Machine Learning

"""#The code and its explanation

##Code explanation

###1)
 The pd.DataFrame(data) creates a pandas DataFrame from the input data. A DataFrame is a two-dimensional labeled data structure with columns that can be of different types.

Exclude_columns: An optional parameter (defaulting to an empty list) that allows you to specify columns to be excluded from one-hot encoding.

###2)
df.select_dtypes(include=['object', 'category']).columns is used to identify columns in the DataFrame that have data types of 'object' (typically used for string data) or 'category' (categorical data). This step identifies which columns are categorical.
###3)

pd.get_dummies(df, columns=categorical_columns) is used to perform one-hot encoding on the identified categorical columns. One-hot encoding converts categorical variables into dummy or indicator variables, creating new binary columns for each category and marking the presence of that category with a 1 or 0.**bold text**

## Code
"""

def pre_processing(data,exclude_columns=[]):
    df = pd.DataFrame(data)
    categorical_columns = (col for col in df.select_dtypes(include=['object', 'category']).columns if col not in exclude_columns)
    df = pd.get_dummies(df, columns=categorical_columns)

    return df

#Testing the functionality of this function using synthetic data.

Artificial_data = {"Name":["Yosi","Yaakov","Ofer"],
                   "Candidate's date of birth":['12/03/20','14/05/19','30/09/74'],
                   "Age":[3,4,50],
                   "Is adult":[0,0,1],
                   "City":["TLV","Jerusalem","Herzeliya"]


}

#Prepare the data for ML

#excluded columns
ex_columns = ["Name","Candidate's date of birth"]

new_art_df = pre_processing(Artificial_data,ex_columns)

new_art_df

